apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName  }}
  labels:
    app: {{ .Values.appName  }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5678
  selector:
    app: {{ .Values.appName  }}

