apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: le-crt
spec:
  secretName: tls-secret
  dnsNames:
  - "*.afeezadeboye.site"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.afeezadeboye.site"